### ISSUE TITLE
Run error: terminate called after throwing an instance of 'char const*'

### ISSUE THREAD

**Issue by Diti** [gzankevich/MySequel#1]
I cloned your repository, ran `cmake src/`, installed packages `libmysqld-dev` and `ncurses-dev`, used `make` to compile, and ran the `mysequel` executable.

The program doesn’t launch. Its only output is:

```
terminate called after throwing an instance of 'char const*'
                                                            zsh: abort      ./mysequel

```

I do not have the time to investigate the issue, though. Sorry!

**Comment by marsjaninzmarsa** [comment]
+1 for issue, but I ran cmake ./ (cause of CMakeLists.txt in root folder), but result is the same...

**Comment by chanchann** [comment]
You should input your own user and password and databse.

**Comment by Diti** [comment]
This project seems unmaintained. I will be switching to [`mycli`](/dbcli/mycli) (and [`pgcli`](/dbcli/pgcli), etc.), and will be closing this issue so that it doesn’t show up in my GitHub dashboard.
